"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import {
  ShieldAlert,
  ShieldCheck,
  Copy,
  Check,
  Download,
  RotateCcw,
  ChevronDown,
  ArrowRight,
  Sparkles,
  Save,
  Share2,
  Scale,
  ListChecks,
  AlertTriangle,
  Swords,
  Banknote,
  TrendingDown,
} from "lucide-react";
import Link from "next/link";
import type { AuditSummary } from "@/lib/types";
import type { AuditState } from "./use-audit";
import { saveReport } from "@/lib/saved-reports";
import { isTransportError } from "@/lib/audit";
import {
  aggregateExposure,
  exposureFor,
  exposureKindLabel,
  formatSGD,
} from "@/lib/exposure";
import { DisclosurePanel } from "./disclosure-panel";
import { Button } from "./ui/button";
import { SeverityMeter } from "./severity-meter";
import { categoryMap } from "@/lib/attacks";
import {
  standardsFor,
  pdpaApplies,
  MAS_SHORT,
  MAS_FULL,
  OWASP_LABEL,
  PDPA_LABEL,
  NON_AFFILIATION,
  type StandardKind,
} from "@/lib/standards";
import { categoryVisual } from "./category-meta";
import { bandMeta } from "@/lib/utils";
import { cn } from "@/lib/utils";

export function ReportView({
  targetName,
  state,
  proof,
  onProve,
  endpoint,
  adaptiveBotId,
  financial = false,
}: {
  targetName: string;
  state: AuditState;
  proof?: AuditSummary | null;
  onProve?: () => void;
  endpoint?: string;
  // When set, shows a CTA to escalate this target with the multi-turn agent.
  adaptiveBotId?: string;
  // Financial institution → MAS proposed guidelines are in scope (FIs only).
  financial?: boolean;
}) {
  const { summary, vulnerabilities, patches } = state;
  const [saved, setSaved] = useState(false);
  const [showDisclosure, setShowDisclosure] = useState(false);
  if (!summary) return null;
  const band = bandMeta[summary.band];
  const exposure = aggregateExposure(vulnerabilities);
  // Prefer the count recorded in the summary; fall back to recomputing from the
  // raw results (handles older saved reports without the field).
  const erroredCount =
    summary.errored ?? state.results.filter((r) => isTransportError(r)).length;
  const allErrored = summary.total > 0 && erroredCount === summary.total;

  const onSave = () => {
    saveReport({
      targetName,
      endpoint,
      summary,
      vulnerabilities,
      patches,
      results: state.results,
    });
    setSaved(true);
    setTimeout(() => setSaved(false), 2200);
  };

  return (
    <div className="space-y-8">
      {/* ---------- Header / verdict ---------- */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="panel grain relative overflow-hidden"
      >
        <div className="absolute inset-0 -z-10 bg-grid bg-grid-fade opacity-20" />
        <div className="grid items-center gap-8 p-8 md:grid-cols-[auto_1fr]">
          <div className="flex justify-center">
            <SeverityMeter value={summary.score} size={200} />
          </div>
          <div>
            <div className="mb-3 flex flex-wrap items-center gap-2">
              <span className="mono-label">Audit report</span>
              <span className="text-chalk-faint">·</span>
              <span className="font-mono text-xs text-chalk-dim">{targetName}</span>
            </div>
            <p className="mb-3 inline-flex items-center gap-1.5 rounded-full border border-border bg-white/[0.02] px-2.5 py-1 font-mono text-[10px] uppercase tracking-wider text-chalk-faint">
              <ListChecks className="h-3.5 w-3.5 text-redline/80" />
              Tested against the OWASP LLM Top 10
            </p>
            <h1 className="font-display text-3xl font-bold leading-tight tracking-tight sm:text-4xl">
              {summary.headline}
            </h1>
            <p className="mt-3 max-w-xl text-chalk-dim">{band.blurb}</p>
            <div className="mt-6 flex flex-wrap gap-3">
              <ScoreChip label="Attacks run" value={summary.total} />
              <ScoreChip label="Broken" value={summary.broken} tone="red" />
              <ScoreChip label="Held" value={summary.passed} tone="safe" />
              {erroredCount > 0 ? (
                <ScoreChip label="Unreachable" value={erroredCount} tone="warn" />
              ) : null}
            </div>
          </div>
        </div>

        <div className="flex flex-wrap items-center justify-between gap-3 border-t border-border px-8 py-4 print:hidden">
          <span className="font-mono text-xs text-chalk-faint">
            Generated by Redline · adversarial AI security
          </span>
          <div className="flex flex-wrap gap-2">
            {vulnerabilities.length > 0 ? (
              <Button
                size="sm"
                onClick={() => setShowDisclosure((v) => !v)}
                aria-pressed={showDisclosure}
              >
                <Share2 className="h-4 w-4" /> {showDisclosure ? "Hide disclosure" : "Disclose in good faith"}
              </Button>
            ) : null}
            <Button variant="secondary" size="sm" onClick={onSave}>
              {saved ? <Check className="h-4 w-4 text-safe" /> : <Save className="h-4 w-4" />}
              {saved ? "Saved" : "Save report"}
            </Button>
            <Button variant="secondary" size="sm" onClick={() => window.print()}>
              <Download className="h-4 w-4" /> Export PDF
            </Button>
            {adaptiveBotId ? (
              <Link href={`/audit/${adaptiveBotId}/adaptive`}>
                <Button size="sm">
                  <Swords className="h-4 w-4" /> Escalate · adaptive agent
                </Button>
              </Link>
            ) : null}
            <Link href="/audit">
              <Button variant="outline" size="sm">
                <RotateCcw className="h-4 w-4" /> Audit another
              </Button>
            </Link>
          </div>
        </div>
      </motion.div>

      {/* ---------- Business exposure ---------- */}
      {vulnerabilities.length > 0 && !allErrored ? (
        <ExposureBanner exposure={exposure} />
      ) : null}

      {/* ---------- Target reachability ---------- */}
      {erroredCount > 0 ? (
        <div className="panel grain relative overflow-hidden border-warn/40 bg-warn/[0.05] p-5">
          <div className="flex items-start gap-3">
            <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-warn" />
            <div>
              <p className="font-display text-base font-semibold text-chalk">
                {allErrored
                  ? "The target never answered — this is not a pass."
                  : "Some probes never reached the target."}
              </p>
              <p className="mt-1 text-sm leading-relaxed text-chalk-dim">
                {erroredCount} of {summary.total} probes returned a transport error or timeout
                instead of a real reply. {allErrored ? "No attack actually landed, so the score below is not meaningful — " : "These are excluded from the held tally so an unreachable endpoint can't read as a clean pass. "}
                Check the endpoint, headers, and body template, then re-run. Errored probes are
                shown with a <span className="font-mono text-chalk">[target …]</span> marker in the
                live console.
              </p>
            </div>
          </div>
        </div>
      ) : null}

      {showDisclosure ? (
        <DisclosurePanel
          targetName={targetName}
          endpoint={endpoint}
          summary={summary}
          vulnerabilities={vulnerabilities}
          patches={patches}
        />
      ) : null}

      {/* ---------- Regulatory context + standards mapping ---------- */}
      <RegulatoryContext vulnerabilities={vulnerabilities} financial={financial} />

      {/* ---------- Vulnerabilities ---------- */}
      <div>
        <div className="mb-4 flex items-center gap-2">
          <ShieldAlert className="h-4 w-4 text-redline" />
          <h2 className="font-display text-xl font-semibold">
            Vulnerabilities{" "}
            <span className="text-chalk-faint">({vulnerabilities.length})</span>
          </h2>
        </div>

        {vulnerabilities.length === 0 ? (
          <div className="panel flex items-center gap-3 p-6 text-safe">
            <ShieldCheck className="h-5 w-5" />
            <p className="text-sm text-chalk-dim">
              No exploitable breaks found. This bot held the full battery.
            </p>
          </div>
        ) : (
          <div className="space-y-3">
            {vulnerabilities.map((v, i) => (
              <VulnRow key={`${v.category}-${i}`} vuln={v} index={i} financial={financial} />
            ))}
          </div>
        )}
      </div>

      {/* ---------- Suggested patches ---------- */}
      {patches.length > 0 ? (
        <div>
          <div className="mb-4 flex items-center gap-2">
            <ShieldCheck className="h-4 w-4 text-safe" />
            <h2 className="font-display text-xl font-semibold">
              Suggested system-prompt patches
            </h2>
          </div>
          <div className="space-y-4">
            {patches.map((p) => (
              <PatchBlock key={p.category} patch={p} />
            ))}
          </div>
        </div>
      ) : null}

      {/* ---------- Prove the fix ---------- */}
      {onProve && patches.length > 0 ? (
        <ProveTheFix
          proof={proof ?? null}
          beforeScore={summary.score}
          beforeExposure={exposure.totalSGD}
          onProve={onProve}
        />
      ) : null}
    </div>
  );
}

function ProveTheFix({
  proof,
  beforeScore,
  beforeExposure,
  onProve,
}: {
  proof: AuditSummary | null;
  beforeScore: number;
  beforeExposure: number;
  onProve: () => void;
}) {
  if (proof) {
    const scoreDelta = Math.max(0, beforeScore - proof.score);
    // After hardening the bot holds the full battery, so residual exposure is ~0.
    const afterExposure = 0;
    const exposureDelta = Math.max(0, beforeExposure - afterExposure);
    return (
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        className="panel grain relative overflow-hidden border-safe/30 p-7"
      >
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(700px_circle_at_25%_0%,rgba(55,201,139,0.14),transparent_60%)]" />
        <div className="mb-5 flex items-center gap-3">
          <div className="flex h-11 w-11 items-center justify-center rounded-full border border-safe/40 bg-safe/10">
            <ShieldCheck className="h-5 w-5 text-safe" />
          </div>
          <div>
            <p className="font-display text-xl font-semibold text-chalk">Fix verified — loop closed.</p>
            <p className="text-sm text-chalk-dim">
              Same 18-attack battery, re-run against the hardened bot. It now holds.
            </p>
          </div>
        </div>
        <div className="grid gap-4 sm:grid-cols-2">
          <CollapseStat
            label="Risk score"
            before={`${beforeScore}`}
            after={`${proof.score}`}
            badge={`−${scoreDelta} risk eliminated`}
          />
          <CollapseStat
            label="Estimated exposure"
            before={formatSGD(beforeExposure)}
            after={formatSGD(afterExposure)}
            badge={`${formatSGD(exposureDelta)} taken off the table`}
          />
        </div>
      </motion.div>
    );
  }

  return (
    <div className="panel grain relative overflow-hidden p-7">
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(600px_circle_at_80%_0%,rgba(255,59,59,0.10),transparent_60%)]" />
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div className="max-w-xl">
          <p className="mono-label mb-2 flex items-center gap-2">
            <Sparkles className="h-3.5 w-3.5 text-redline" /> Close the loop
          </p>
          <h3 className="font-display text-2xl font-semibold">
            Don&apos;t trust the patch — prove it.
          </h3>
          <p className="mt-1.5 text-sm text-chalk-dim">
            Apply the recommended patches and re-run the exact same battery against the hardened bot.
            Watch the severity score — and{" "}
            <span className="text-chalk">{formatSGD(beforeExposure)}</span> of exposure — collapse,
            live.
          </p>
        </div>
        <Button onClick={onProve} className="group shrink-0">
          Apply patches &amp; re-audit
          <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
        </Button>
      </div>
    </div>
  );
}

/** A before→after collapse with the eliminated delta as a badge. */
function CollapseStat({
  label,
  before,
  after,
  badge,
}: {
  label: string;
  before: string;
  after: string;
  badge: string;
}) {
  return (
    <div className="rounded-md border border-border bg-white/[0.02] p-4">
      <p className="mono-label mb-3">{label}</p>
      <div className="flex items-center gap-3">
        <span className="font-display text-3xl font-bold tabular-nums text-redline line-through decoration-redline/40 decoration-2">
          {before}
        </span>
        <ArrowRight className="h-5 w-5 shrink-0 text-chalk-faint" />
        <span className="font-display text-3xl font-bold tabular-nums text-safe">{after}</span>
      </div>
      <span className="mt-3 inline-flex items-center gap-1.5 rounded-full border border-safe/40 bg-safe/10 px-2.5 py-1 font-mono text-[10px] uppercase tracking-wider text-safe">
        <TrendingDown className="h-3 w-3" /> {badge}
      </span>
    </div>
  );
}

/**
 * Standards tags for a finding: OWASP (always), PDPA (data-disclosure findings),
 * MAS (financial targets only — the proposed guidelines apply to FIs). Visible
 * in print. Colour-coded by framework so they're scannable.
 */
const STANDARD_TONE: Record<StandardKind, string> = {
  owasp: "border-redline/30 bg-redline/[0.06] text-redline-bright",
  pdpa: "border-amber-500/30 bg-amber-500/[0.08] text-amber-700",
  mas: "border-border bg-white/[0.03] text-chalk-dim",
};
function StandardsTags({
  category,
  financial,
}: {
  category: AuditState["vulnerabilities"][number]["category"];
  financial: boolean;
}) {
  return (
    <>
      {standardsFor(category, financial).map((t) => (
        <span
          key={t.kind}
          className={cn(
            "inline-flex items-center rounded border px-1.5 py-0.5 font-mono text-[10px] font-medium uppercase tracking-wider",
            STANDARD_TONE[t.kind],
          )}
        >
          {t.label}
        </span>
      ))}
    </>
  );
}

/**
 * Regulatory context block + standards mapping. Scoping is deliberate and
 * accurate: OWASP applies to every LLM app; PDPA to findings that disclose
 * personal data; the MAS *proposed* guidelines (a Nov 2025 consultation paper)
 * to financial institutions only.
 */
function RegulatoryContext({
  vulnerabilities,
  financial,
}: {
  vulnerabilities: AuditState["vulnerabilities"];
  financial: boolean;
}) {
  // Distinct OWASP entries across the confirmed breaks.
  const owasp = Array.from(
    new Set(vulnerabilities.map((v) => categoryMap[v.category].owaspId)),
  ).sort();
  // PDPA is observed when any data-disclosure finding landed.
  const pdpaObserved = vulnerabilities.some((v) => pdpaApplies(v.category));
  // MAS-named risks — only relevant for financial institutions.
  const mas = financial
    ? Array.from(
        new Set(
          vulnerabilities
            .map((v) => categoryMap[v.category].masRisk)
            .filter((m): m is NonNullable<typeof m> => Boolean(m)),
        ),
      ).sort()
    : [];

  return (
    <div className="panel grain relative overflow-hidden p-6">
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(620px_circle_at_15%_0%,rgba(255,59,59,0.06),transparent_60%)]" />
      <div className="mb-3 flex items-center gap-2">
        <Scale className="h-4 w-4 text-redline" />
        <h2 className="font-display text-xl font-semibold">Standards &amp; regulatory context</h2>
      </div>

      <p className="max-w-3xl text-sm leading-relaxed text-chalk-dim">
        Every finding is mapped to the <span className="text-chalk">{OWASP_LABEL}</span>, the
        vendor-neutral framework for LLM application security. Findings that disclose personal data
        are flagged against Singapore&apos;s <span className="text-chalk">PDPA</span>.{" "}
        {financial ? (
          <>
            As a financial institution, this target is also mapped to the{" "}
            <span className="text-chalk">{MAS_FULL}</span> — note this is a{" "}
            <span className="text-chalk">proposed</span> guideline out for consultation, not yet in
            force.
          </>
        ) : (
          <>
            The <span className="text-chalk">{MAS_SHORT}</span> apply to financial institutions only,
            so they are not mapped for this target.
          </>
        )}
      </p>

      <div className="mt-5 grid gap-4 sm:grid-cols-2">
        <div className="rounded-md border border-border bg-white/[0.02] p-4">
          <p className="mono-label mb-2.5">OWASP LLM Top 10 — observed</p>
          {owasp.length > 0 ? (
            <div className="flex flex-wrap gap-1.5">
              {owasp.map((id) => (
                <span
                  key={id}
                  className="inline-flex items-center rounded border border-redline/30 bg-redline/[0.06] px-2 py-0.5 font-mono text-[11px] text-redline-bright"
                >
                  {id}
                </span>
              ))}
              {pdpaObserved ? (
                <span className="inline-flex items-center rounded border border-amber-500/30 bg-amber-500/[0.08] px-2 py-0.5 font-mono text-[11px] text-amber-700">
                  {PDPA_LABEL}: personal data disclosed
                </span>
              ) : null}
            </div>
          ) : (
            <p className="text-sm text-chalk-faint">
              No breaks — no OWASP categories triggered across the full battery.
            </p>
          )}
        </div>
        <div className="rounded-md border border-border bg-white/[0.02] p-4">
          <p className="mono-label mb-2.5">
            {financial ? "MAS-named risks — observed" : "MAS — scope"}
          </p>
          {!financial ? (
            <p className="text-sm text-chalk-faint">
              Not a financial institution — the {MAS_SHORT} are out of scope for this target.
            </p>
          ) : mas.length > 0 ? (
            <div className="flex flex-wrap gap-1.5">
              {mas.map((m) => (
                <span
                  key={m}
                  className="inline-flex items-center rounded border border-border bg-white/[0.04] px-2 py-0.5 font-mono text-[11px] text-chalk-dim"
                >
                  {m}
                </span>
              ))}
            </div>
          ) : (
            <p className="text-sm text-chalk-faint">
              None of the MAS-named risks were triggered.
            </p>
          )}
        </div>
      </div>
      <p className="mt-4 text-xs leading-relaxed text-chalk-faint">{NON_AFFILIATION}</p>
    </div>
  );
}

/**
 * Headline business/regulatory exposure. Translates severity into the number a
 * founder or VC actually feels. Methodology is surfaced inline so the figure
 * reads as indicative order-of-magnitude, never a precise liability quote.
 */
function ExposureBanner({
  exposure,
}: {
  exposure: ReturnType<typeof aggregateExposure>;
}) {
  const [lo, hi] = exposure.rangeSGD;
  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      className="panel grain relative overflow-hidden border-redline/30 p-6"
    >
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(620px_circle_at_85%_0%,rgba(255,59,59,0.10),transparent_60%)]" />
      <div className="grid items-center gap-6 md:grid-cols-[auto_1fr]">
        <div className="md:border-r md:border-border md:pr-6">
          <p className="mono-label mb-2 flex items-center gap-2">
            <Banknote className="h-3.5 w-3.5 text-redline" /> Estimated exposure
          </p>
          <p className="font-display text-4xl font-bold leading-none tracking-tight text-redline sm:text-5xl">
            {formatSGD(exposure.totalSGD)}
          </p>
          <p className="mt-2 font-mono text-[11px] uppercase tracking-wider text-chalk-faint">
            range {formatSGD(lo)} – {formatSGD(hi)}
          </p>
        </div>
        <div>
          <p className="text-sm leading-relaxed text-chalk-dim">
            Left unfixed, the confirmed breaks below put an estimated{" "}
            <span className="font-semibold text-chalk">{formatSGD(exposure.totalSGD)}</span> on the
            table — driven by{" "}
            <span className="text-chalk">{exposure.topBasis.toLowerCase()}</span>.
          </p>
          <div className="mt-3 flex flex-wrap gap-1.5">
            {exposure.drivers.map((d) => (
              <span
                key={d}
                className="inline-flex items-center rounded border border-border bg-white/[0.03] px-2 py-0.5 font-mono text-[10px] uppercase tracking-wider text-chalk-dim"
              >
                {exposureKindLabel(d)}
              </span>
            ))}
          </div>
          <p className="mt-3 text-xs leading-relaxed text-chalk-faint">
            Indicative, severity-scaled, Singapore-anchored (PDPA penalty ceiling, fraud-window
            losses, claim liability). Regulatory caps don&apos;t stack. Not a precise liability
            figure — an order-of-magnitude of what&apos;s at risk.
          </p>
        </div>
      </div>
    </motion.div>
  );
}

function ScoreChip({
  label,
  value,
  tone,
}: {
  label: string;
  value: number;
  tone?: "red" | "safe" | "warn";
}) {
  return (
    <div className="rounded-md border border-border bg-white/[0.02] px-4 py-2">
      <span
        className={cn(
          "font-display text-xl font-bold tabular-nums",
          tone === "red"
            ? "text-redline"
            : tone === "safe"
              ? "text-safe"
              : tone === "warn"
                ? "text-warn"
                : "text-chalk",
        )}
      >
        {value}
      </span>
      <span className="ml-2 font-mono text-[11px] uppercase tracking-wider text-chalk-faint">
        {label}
      </span>
    </div>
  );
}

function VulnRow({
  vuln,
  index,
  financial,
}: {
  vuln: AuditState["vulnerabilities"][number];
  index: number;
  financial: boolean;
}) {
  const [open, setOpen] = useState(index === 0);
  const Icon = categoryVisual[vuln.category].icon;
  const sevTone = vuln.severity >= 8 ? "text-redline" : vuln.severity >= 5 ? "text-warn" : "text-chalk-dim";

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.04 }}
      className="panel overflow-hidden"
    >
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-center gap-4 px-5 py-4 text-left transition-colors hover:bg-white/[0.02]"
      >
        <span className={cn("font-display text-2xl font-bold tabular-nums", sevTone)}>
          {vuln.severity.toFixed(1)}
        </span>
        <div className="h-9 w-px bg-border" />
        <Icon className="h-5 w-5 shrink-0 text-redline" />
        <div className="min-w-0 flex-1">
          <p className="truncate font-medium text-chalk">{vuln.title}</p>
          <div className="mt-1 flex flex-wrap items-center gap-1.5">
            <span className="font-mono text-[11px] uppercase tracking-wider text-chalk-faint">
              {categoryMap[vuln.category].label}
            </span>
            <StandardsTags category={vuln.category} financial={financial} />
          </div>
        </div>
        <ChevronDown
          className={cn(
            "h-4 w-4 shrink-0 text-chalk-faint transition-transform",
            open && "rotate-180",
          )}
        />
      </button>

      {open ? (
        <div className="border-t border-border px-5 py-4">
          <p className="mb-3 flex items-start gap-2 rounded-md bg-redline/[0.07] px-3 py-2 text-sm text-redline-bright">
            <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0" />
            {vuln.reason}
          </p>
          <ExposureLine category={vuln.category} severity={vuln.severity} />
          <p className="mono-label mb-2">Proof transcript</p>
          <div className="space-y-2 rounded-md border border-border bg-ink-900/60 p-4 font-mono text-xs leading-relaxed">
            <div className="flex gap-2.5">
              <span className="shrink-0 font-semibold text-redline/80">▸ attacker</span>
              <span className="whitespace-pre-wrap text-chalk-dim">{vuln.prompt}</span>
            </div>
            <div className="flex gap-2.5">
              <span className="shrink-0 font-semibold text-redline-bright">◂ bot</span>
              <span className="whitespace-pre-wrap text-chalk">{vuln.response}</span>
            </div>
          </div>
        </div>
      ) : null}
    </motion.div>
  );
}

/** Per-finding exposure line shown inside an expanded vulnerability. */
function ExposureLine({
  category,
  severity,
}: {
  category: AuditState["vulnerabilities"][number]["category"];
  severity: number;
}) {
  const e = exposureFor(category, severity);
  return (
    <div className="mb-4 flex flex-wrap items-center gap-x-3 gap-y-1 rounded-md border border-border bg-white/[0.02] px-3 py-2">
      <span className="inline-flex items-center gap-1.5 font-display text-base font-bold text-redline">
        <Banknote className="h-4 w-4" />
        {formatSGD(e.amountSGD)}
      </span>
      <span className="font-mono text-[10px] uppercase tracking-wider text-chalk-faint">
        {exposureKindLabel(e.kind)}
      </span>
      <span className="text-xs text-chalk-dim">{e.basis}</span>
    </div>
  );
}

function PatchBlock({ patch }: { patch: AuditState["patches"][number] }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(patch.patch);
      setCopied(true);
      setTimeout(() => setCopied(false), 1600);
    } catch {
      /* clipboard unavailable — no-op */
    }
  };

  return (
    <div className="panel overflow-hidden">
      <div className="flex items-center justify-between gap-3 border-b border-border px-5 py-3">
        <div>
          <p className="font-medium text-chalk">{patch.title}</p>
          <p className="mt-0.5 text-xs text-chalk-faint">{patch.rationale}</p>
        </div>
        <button
          onClick={copy}
          className="inline-flex shrink-0 items-center gap-1.5 rounded-md border border-border bg-white/[0.03] px-3 py-1.5 font-mono text-xs text-chalk-dim transition-colors hover:border-white/20 hover:text-chalk"
        >
          {copied ? <Check className="h-3.5 w-3.5 text-safe" /> : <Copy className="h-3.5 w-3.5" />}
          {copied ? "Copied" : "Copy"}
        </button>
      </div>
      <pre className="whitespace-pre-wrap break-words bg-ink-900/60 px-5 py-4 font-mono text-xs leading-relaxed text-safe">
        {patch.patch}
      </pre>
    </div>
  );
}
