import type { AuditSummary, Vulnerability, PromptPatch } from "./types";
import { categoryMap } from "./attacks";
import { bandMeta } from "./utils";

// ===========================================================================
// Responsible-disclosure tooling. Redline is for AUTHORISED testing and
// GOOD-FAITH coordinated disclosure: when you find a break in a bot you don't
// own, you report it to the company so they can fix it — you never retain or
// publish another person's leaked data. PII the bot leaks is auto-redacted in
// everything that leaves Redline.
// ===========================================================================

/** Mask personal data a bot may have leaked, so findings can be shared safely. */
export function redactPII(text: string): string {
  if (!text) return text;
  return (
    text
      // emails -> keep first char + domain: s***@gmail.com
      .replace(/\b([A-Za-z0-9._%+-])[A-Za-z0-9._%+-]*@([A-Za-z0-9.-]+\.[A-Za-z]{2,})\b/g, "$1***@$2")
      // Singapore phone numbers (+65 / 8/9 + 7 digits)
      .replace(/(\+?65[\s-]?)?\b[689]\d{3}[\s-]?\d{4}\b/g, "[redacted-phone]")
      // NRIC / FIN
      .replace(/\b[STFGstfg]\d{7}[A-Za-z]\b/g, "[redacted-id]")
      // long digit runs (ids, card-ish)
      .replace(/\b\d{9,}\b/g, "[redacted-number]")
  );
}

export type DisclosureInput = {
  targetName: string;
  endpoint?: string;
  companyName?: string;
  reporterName?: string;
  reporterContact?: string;
  dateISO: string;
  summary: AuditSummary;
  vulnerabilities: Vulnerability[];
  patches: PromptPatch[];
  redact: boolean;
};

/** Build a professional, good-faith coordinated-disclosure report (Markdown). */
export function buildDisclosureMarkdown(input: DisclosureInput): string {
  const {
    targetName,
    endpoint,
    companyName,
    reporterName,
    reporterContact,
    dateISO,
    summary,
    vulnerabilities,
    patches,
    redact,
  } = input;

  const date = dateISO.slice(0, 10);
  const who = companyName || targetName;
  const r = (s: string) => (redact ? redactPII(s) : s);
  const band = bandMeta[summary.band];

  const findings = vulnerabilities
    .map((v, i) => {
      const patch = patches.find((p) => p.category === v.category);
      return `### Finding ${i + 1} — ${v.title}  \`severity ${v.severity}/10\`
**Category:** ${categoryMap[v.category].label}

**What happens:** ${v.reason}

**Reproduction**
\`\`\`
Attacker → ${r(v.prompt)}

Bot      → ${r(v.response)}
\`\`\`
${patch ? `**Recommended remediation:**\n${patch.patch.trim()}\n` : ""}`;
    })
    .join("\n\n---\n\n");

  return `# Security disclosure — ${who}

**Date:** ${date}
**Target:** ${targetName}${endpoint ? ` (\`${endpoint}\`)` : ""}
**Reported by:** ${reporterName || "a security researcher"}${reporterContact ? ` · ${reporterContact}` : ""}
**Tooling:** Redline (adversarial AI agent audit)

---

## Good-faith notice
This report is shared in good faith so that you can fix the issues below. The testing
sent only conversational messages to your public chatbot — no infrastructure was
attacked, no denial-of-service was attempted, and **no personal data was retained or
redistributed** (any personal data the bot disclosed is redacted in this report). I am
happy to coordinate on a fix timeline and to re-test once you have patched.

## Summary
- **Overall risk:** ${summary.score}/100 — **${band.label}**
- **Attacks run:** ${summary.total} · **confirmed breaks:** ${summary.broken}
- ${summary.headline}

${
  vulnerabilities.length === 0
    ? "No exploitable findings — the bot held the full battery."
    : `## Findings (${vulnerabilities.length})\n\n${findings}`
}

---

*Generated by Redline. Please treat this report as confidential until remediated.*
`;
}

/** A short, friendly email body to accompany the report. */
export function buildDisclosureEmail(input: DisclosureInput): { subject: string; body: string } {
  const who = input.companyName || input.targetName;
  const subject = `Good-faith security disclosure — ${who} chatbot (${input.summary.broken} issue${input.summary.broken === 1 ? "" : "s"} found)`;
  const body = `Hello ${who} team,

I was testing your AI chatbot and found ${input.summary.broken} issue${input.summary.broken === 1 ? "" : "s"} I think you'll want to fix. I'm reporting this in good faith — I only sent normal chat messages, retained no personal data, and haven't shared this anywhere.

Overall risk: ${input.summary.score}/100 (${bandMeta[input.summary.band].label}).

The full report with reproduction steps and suggested fixes is attached/below. Happy to walk through it and re-test once you've patched.

Best regards,
${input.reporterName || ""}${input.reporterContact ? `\n${input.reporterContact}` : ""}`;
  return { subject, body };
}
